### ISSUE TITLE
Using the root Activity ViewModelStore

### ISSUE THREAD

**Issue by miquelbeltran** [devindi/mapwall#22]
Hello :)

Someone linked me your project in an issue of one of my libraries: https://github.com/miquelbeltran/conductor-viewmodel/issues/1 

And I wanted to report an issue I noticed.

In the BaseController class https://github.com/devindi/mapwall/blob/1ad9bae0e8d2cd588a4e3ce1bb90a35ec764e017/app/src/main/java/com/devindi/wallpaper/misc/BaseController.kt#L13 you are providing the ViewModelStore from the root activity in order to provide ViewModels to your Controllers.

```
override fun getViewModelStore(): ViewModelStore {
        return (activity as FragmentActivity).viewModelStore
    }
```

The problem is that your Activity will hold all ViewModels all the time during its lifecycle. So if you open one Controller, load a ViewModel, then close it, then open it again, the ViewModel instance is the same, and any state stored in that ViewModel is going to be still there.

The ViewModel onCleared method is not going to be called until the Activity is destroyed (which may never happen until the app is closed).

A solution to this problem is to let Controllers have their own ViewModelStore. You can accomplish that just by adding a ViewModelStore instance to your BaseController (or by using my little library).

This is an example of a Controller with a ViewModelStore: https://github.com/miquelbeltran/conductor-viewmodel/blob/master/conductor-viewmodel/src/main/java/work/beltran/conductorviewmodel/ViewModelController.java

I hope you find this information useful and I was friendly enough! Let me know if you have any questions.

**Comment by devindi** [comment]
Hi @miquelbeltran 
Thank you for your note, it's very useful for me. 
Unfortunately I can't use your library as is because koin requires Activity/Fragment/ViewModelStoreOwner so I made a hybrid solution. 

https://github.com/devindi/mapwall/blob/82be6eafa79a15514933ac9b9efd154215c5387f/app/src/main/java/com/devindi/wallpaper/misc/BaseController.kt#L11
