### ISSUE TITLE
Logo Design for Mapwall

### ISSUE THREAD

**Issue by baranpirincal** [devindi/mapwall#8]
Hey!

I am graphic designer and my aim is make my portfolio better with supporting open source projects in field of graphics. If you interested, I can design a logo for Mapwall. 

I am waiting your comment, have a nice day!

Best Regards
Baran

**Comment by devindi** [comment]
Hi Baran!

Thanks for your proposal. It would be great if you will create logo for the project.
Here is current application icon: https://github.com/devindi/mapwall/blob/master/files/icon/icon_raw_stars.svg
Application is placed in Google Play where you may check out some screenshots and build https://play.google.com/store/apps/details?id=com.devindi.wallpaper

My first idea about icon/logo was to combine wallpaper icon and image of Earth but you are not limited by this idea. 

Thanks,
Andrew

**Comment by baranpirincal** [comment]
Hey @devindi 

Here is my proposal for Mapwall. I combined wallpaper icon and world. I hope you like it!

![worldmap](https://user-images.githubusercontent.com/37786733/45910940-24c13580-be16-11e8-93d2-21a83b951646.jpg)

**Comment by devindi** [comment]
Great work, thanks a lot!

Will you create PR with this amazing logo?

**Comment by baranpirincal** [comment]
@devindi 

I created pr and uploaded all necessary files, have a nice day! :)

**Comment by devindi** [comment]
Close because logo is ready here #15
